"""Update charity project model

Revision ID: fc86fcb85556
Revises: e361dc7a3eee
Create Date: 2024-10-06 14:32:00.052391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc86fcb85556'
down_revision: Union[str, None] = 'e361dc7a3eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    op.drop_table('charityproject')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charityproject',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('desciption', sa.VARCHAR(), nullable=False),
    sa.Column('full_amount', sa.INTEGER(), nullable=False),
    sa.Column('invested_amount', sa.INTEGER(), nullable=False),
    sa.Column('fully_invested', sa.BOOLEAN(), nullable=False),
    sa.Column('create_data', sa.DATETIME(), nullable=False),
    sa.Column('close_date', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('donation',
    sa.Column('comment', sa.VARCHAR(), nullable=False),
    sa.Column('full_amount', sa.INTEGER(), nullable=False),
    sa.Column('invested_amount', sa.INTEGER(), nullable=False),
    sa.Column('fully_invested', sa.BOOLEAN(), nullable=False),
    sa.Column('create_data', sa.DATETIME(), nullable=False),
    sa.Column('close_date', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
